# Generated by Django 3.0 on 2019-12-16 08:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theloai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_the_loai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tintuc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=1000)),
                ('tom_tat', models.TextField(default={})),
                ('hinh', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ngaytao', models.DateTimeField(auto_now=True)),
                ('noidung', ckeditor.fields.RichTextField()),
                ('theloai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Theloai')),
            ],
        ),
    ]
